<?php
    $arrayEnglish = array(
        array("ser/estar", "am", "was", "been"),
        array("ganarle (a alguien)", "beat", "beat", "beaten"),
        array("empezar", "begin", "began", "begun"),
        array("doblar", "bend", "bent", "bent"),
        array("morder", "bite", "bit", "bitten"),
        array("soplar", "blow", "blew", "blown"),
        array("romper", "break", "broke", "broken"),
        array("llevar, traer", "bring", "brought", "brought"),
        array("construir", "build", "built", "built"),
        array("comprar", "buy", "bought", "bought"),
        array("coger", "catch", "caught", "caught"),
        array("elegir", "choose", "chose", "chosen"),
        array("venir", "come", "came", "come"),
        array("costar", "cost", "cost", "cost"),
        array("hacer", "do", "did", "done"),
        array("dibujar", "draw", "drew", "drawn"),
        array("soñar", "dream", "dreamed", "dreamed"),
        array("conducir", "drive", "drove", "driven"),
        array("beber", "drink", "drank", "drunk"),
        array("comer", "eat", "ate", "eaten"),
        array("caer", "fall", "fell", "fallen"),
        array("sentir", "feel", "felt", "felt"),
        array("luchar", "fight", "fought", "fought"),
        array("encontrar", "find", "found", "found"),
        array("volar", "fly", "flew", "flown"),
        array("olvidar", "forget", "forgot", "forgotten"),
        array("perdonar", "forgive", "forgave", "forgiven"),
        array("conseguir", "get", "got", "gotten"),
        array("dar", "give", "gave", "given"),
        array("ir", "go", "went", "gone"),
        array("crecer", "grow", "grew", "grown"),
        array("tener", "have", "had", "had"),
        array("oír", "hear", "heard", "heard"),
        array("esconder", "hide", "hid", "hidden"),
        array("golpear", "hit", "hit", "hit"),
        array("sujetar", "hold", "held", "held"),
        array("doler", "hurt", "hurt", "hurt"),
        array("guardar", "keep", "kept", "kept"),
        array("saber", "know", "knew", "known"),
        array("aprender", "learn", "learned", "learned"),
        array("marcharse", "leave", "left", "left"),
        array("prestar", "lend", "lent", "lent"),
        array("permitir", "let", "let", "let"),
        array("perder", "lose", "lost", "lost"),
        array("hacer, fabricar", "make", "made", "made"),
        array("significar, querer decir", "mean", "meant", "meant"),
        array("conocer por primera vez, quedar", "meet", "met", "met"),
        array("pagar", "pay", "paid", "paid"),
        array("poner", "put", "put", "put"),
        array("leer", "read", "read", "read"),
        array("sonar, llamar por teléfono", "ring", "rang", "rung"),
        array("levantar", "rise", "rose", "risen"),
        array("correr", "run", "ran", "run"),
        array("decir", "say", "said", "said"),
        array("ver", "see", "saw", "seen"),
        array("vender", "sell", "sold", "sold"),
        array("enviar", "send", "sent", "sent"),
        array("mostrar, demostrar", "show", "showed", "shown"),
        array("cerrar", "shut", "shut", "shut"),
        array("cantar", "sing", "sang", "sung"),
        array("sentarse", "sit", "sat", "sat"),
        array("dormir", "sleep", "slept", "slept"),
        array("hablar", "speak", "spoke", "spoken"),
        array("gastar", "spend", "spent", "spent"),
        array("estar de pie", "stand", "stood", "stood"),
        array("nadar", "swim", "swam", "swum"),
        array("tomar", "take", "took", "taken"),
        array("enseñar", "teach", "taught", "taught"),
        array("contar, decirle a alguien", "tell", "told", "told"),
        array("pensar", "think", "thought", "thought"),
        array("lanzar, arrojar", "throw", "threw", "thrown"),
        array("entender", "understand", "understood", "understood"),
        array("despertar", "wake", "woke", "woken"),
        array("llevar puesto, ponerse", "wear", "wore", "worn"),
        array("ganar", "win", "won", "won"),
        array("escribir", "write", "wrote", "written")
    );
?>